# ########################################################### #
# Pyxel detector simulation framework                         #
#                                                             #
# Example yaml configuration file                             #
# CCD Photon Transfer Curve with parametric analysis mode     #
# Created by D. Lucsanyi (ESA)                                #
# ########################################################### #

simulation:

  mode: parametric

  parametric:
    parametric_mode: sequential
    parameters:
      - key: pipeline.photon_generation.illumination.arguments.level
        values: numpy.unique(numpy.logspace(0, 6, 100, dtype=int))

  outputs:
    output_folder:  'examples/PTC/outputs'
    parametric_plot:
      x:  'detector.image.mean'
      y:  'detector.image.std_deviation'
      plot_args:
        title: 'CCD Photon Transfer Curve'
        xscale: 'log'
        yscale: 'log'
        xlim: [1., 2.e+6]
        ylim: [1., 3.e+4]
        grid: true

detector:
  class: pyxel.detectors.ccd.CCD

  geometry:
    class: pyxel.detectors.ccd_geometry.CCDGeometry

    row:   100                          # pixels
    col:   100                          # pixels
    total_thickness: 10.                # um
    pixel_vert_size: 10.                # um
    pixel_horz_size: 10.                # um

  material:
    class: pyxel.detectors.material.Material
    material: 'silicon'

  environment:
    class: pyxel.detectors.environment.Environment

  characteristics:
    class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
    qe: 0.5                 # -
    eta: 1.                 # e/photon
    sv: 1.e-6               # V/e
    amp: 0.8                # V/V
    a1: 100.                # V/V
    a2: 65536               # DN/V
    fwc: 100000             # e
    fwc_serial: 200000      # e

pipeline:
  class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline

  # -> photons
  photon_generation:
    - name: illumination
      func: pyxel.models.photon_generation.illumination.illumination
      enabled: true
      arguments:
          level: 0
    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise.shot_noise
      enabled: true

  # photons -> photons
  optics:

  # photons -> charges
  charge_generation:
    - name: photoelectrons
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion
      enabled: true

  # charges -> pixels
  charge_collection:
    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true
    - name: fixed_pattern_noise
      func: pyxel.models.charge_collection.fix_pattern_noise.fix_pattern_noise
      enabled: true
      arguments:
        pix_non_uniformity: data/non_uniformity_array_normal_random_dist.data
    - name: full_well
      func: pyxel.models.charge_collection.full_well.simple_full_well
      enabled: true

  # pixels -> pixels
  charge_transfer:

  # pixels -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true
    - name: output_node_noise
      func: pyxel.models.charge_measurement.readout_noise.output_node_noise
      enabled: true
      arguments:
        std_deviation: 1.e-6   # Volt

  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true
    - name: simple_processing
      func: pyxel.models.readout_electronics.digitization.simple_processing
      enabled: true



