# ########################################################### #
# Pyxel detector simulation framework                         #
#                                                             #
# Example YAML configuration file                             #
# Exposure mode combining different detector effect models    #                         
# ########################################################### #


# yaml-language-server: $schema=https://esa.gitlab.io/pyxel/doc/latest/pyxel_schema.json
exposure:

  readout:
    non_destructive:  false

  # outputs:
    # output_folder: "/Users/georgeseabroke/pyxel-examples/pyxel_data_analysis/ARRAKIHS/set02/output"
    # save_data_to_file:
      # - detector.image.array:   ['fits']
      
cmos_detector:

  geometry:

    row: 100 # 4340                # pixel VIS-VDA-DES-0010
    col: 100 # 4500                # pixel VIS-VDA-DES-0010
    total_thickness: 20.    # um VIS-VDA-DES-0040
    pixel_vert_size: 100.    # um VIS-VDA-DES-0020
    pixel_horz_size: 100.    # um VIS-VDA-DES-0020
    pixel_scale: 0.137518       # arcsec/pixel

  environment:
    temperature: 203.15        # K: ARK-DTF#4-ESA-v1.pptx slide 6, VIS-VDA-THM-0010 ([180-320] K VIS-VDA-THM-0020)

  characteristics:
    quantum_efficiency: 0.7                 # wavelength dependent 
    charge_to_volt_conversion: 0.00009602181      # V/e CIS303-304  Preliminary Characterisation results-commercially-sensitive.pdf slide 19: 8011 ADU/V = 0.00012482836 V/ADU = 0.00012482836 * (1/1.3) ADU/e = 0.00009602181 V/e
    gain_array_path: "gain_array.npy"
    #pre_amplification: 100                 # V/V
    pre_amplification: 1                 # V/V High Gain, Low Full Well (LFW) mode
    adc_bit_resolution: 14                  # 14-bit (ADC saturation at 16383 ADU)
    adc_voltage_range: [0.,14.]               # CIS300 family operating modes.pdf slide 19
    full_well_capacity: 21299.2              # ARK-DTF#4-ESA-v1.pptx: Transfer gain = 1.3-1.4 e/ADU -> 16384 ADU * 1.3 e/ADU = 21299.2 electrons


pipeline:
  # -> photon
  photon_collection:
    - name: load_image
      func: pyxel.models.photon_collection.load_image
      enabled: true
      arguments:
        image_file: /home/zc/code/Pyxel/data/Pleiades_HST.fits
        align: "center"
        
    - name: shot_noise
      func: pyxel.models.photon_collection.shot_noise
      enabled: false
      
    - name: optical_psf
      func: pyxel.models.photon_collection.optical_psf
      enabled: false
      arguments:
        fov_arcsec: 5 # FOV in arcseconds
        wavelength: 600  # wavelength in nm
        optical_system:
          - item: CircularAperture
            radius: 3.0

    - name: shield_box
      func: pyxel.models.photon_collection.shield_box
      enabled: false
      arguments:
        shield_start: [20, 20]
        shield_end: [30, 50]

    - name: shield_border
      func: pyxel.models.photon_collection.shield_border
      enabled: true
      arguments:
        width: 8

  # photon -> charge
  charge_generation:
    - name: photoelectrons
      func: pyxel.models.charge_generation.simple_conversion
      enabled: true
      
    - name: simpe_dark_current
      func: pyxel.models.charge_generation.simple_dark_current
      enabled: false
      arguments:
        dark_rate: 100
        
    - name: cosmix
      func: pyxel.models.charge_generation.cosmix
      enabled: false
      arguments:
        simulation_mode: cosmic_ray
        running_mode: stepsize
        particle_type: proton
        initial_energy: 100.          # MeV
        particles_per_second: 200
        incident_angles:
        starting_position:
        spectrum_file: 'data/proton_L2_solarMax_11mm_Shielding.txt'
        seed: 4321
        progressbar: false

  # charge -> pixel
  charge_collection:
    - name: simple_collection
      func: pyxel.models.charge_collection.simple_collection
      enabled: true
      
    - name: full_well
      func: pyxel.models.charge_collection.simple_full_well
      enabled: false
      
    - name: fixed_pattern_noise
      func: pyxel.models.charge_collection.fixed_pattern_noise
      enabled: false
      arguments:
        filename: "data/noise.npy"
        align: "top_right"

  # pixel -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.simple_measurement
      enabled: true

    - name: non_linearity
      func: pyxel.models.charge_measurement.output_node_linearity_poly_user_array
      enabled: true
      arguments:
        path: "test_nonlinearity_array_100x100.npy"
      
    - name: dc_offset
      func: pyxel.models.charge_measurement.dc_offset
      enabled: true
      arguments:
        offset: 1
        
    - name: ktc_noise
      func: pyxel.models.charge_measurement.ktc_noise
      enabled: false
      arguments:
        node_capacitance: 30.e-15
        
      
    - name: output_noise
      func: pyxel.models.charge_measurement.output_node_noise_cmos
      enabled: true
      arguments:
        readout_noise: 2.33 # 2.33 e/1.3 e/ADU = 1.8 ADU
        readout_noise_std: 0 #

    - name: fixed_readout_noise
      func: pyxel.models.charge_measurement.fixed_readout_noise
      enabled: false
      arguments:
        filename: /home/zc/code/Pyxel/noise_dump.txt
      
  # signal -> image
  readout_electronics:
  
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.simple_amplifier
      enabled: false
  
    - name: simple_adc
      func: pyxel.models.readout_electronics.simple_adc
      enabled: true
    
  data_processing:

    - name: apply_gain
      func: pyxel.models.data_processing.apply_gain
      enabled: true

#########
# Pyxel version: 2.6.1
#########
