# ###############
### Pyxel configuration file for CCD detectors
### David Lucsanyi
# ###############

simulation:

  mode: calibration

  calibration:
    calibration_mode:     pipeline
    result_type:          pixel
    result_fit_range:     [538, 578, 0, 1]
    target_data_path:     ['data/flex/target/target_flex_ds7_ch0_1ke.txt']
    target_fit_range:     [538, 578, 0, 1]
    seed:                 60336
    fitness_function:
      func:               pyxel.calibration.fitness.sum_of_abs_residuals
      arguments:
    algorithm:
      type:               sade
      generations:        20
      population_size:    1000
      variant:            2
    parameters:
      - key:              pipeline.charge_transfer.cdm.arguments.beta_p
        values:           _
        logarithmic:      false
        boundaries:       [1.e-1, 1.]
      - key:              pipeline.charge_transfer.cdm.arguments.tr_p
        values:           [_, _, _, _]
        logarithmic:      true
        boundaries:       [100.e-6, 1.]
      - key:              pipeline.charge_transfer.cdm.arguments.nt_p
        values:           [_, _, _, _]
        logarithmic:      true
        boundaries:       [1.e-1, 1.e+2]
      - key:              pipeline.charge_transfer.cdm.arguments.sigma_p
        values:           [_, _, _, _]
        logarithmic:      true
        boundaries:       [1.e-20, 1.e-12]

  outputs:
    output_folder:        'outputs/cdm_calibration/flex/'
    output_format:
    calibration_plot:
      champions_plot:
        plot_args:
          yscale: 'log'
      population_plot:
        columns: [3, 7]
        plot_args:
          xscale: 'log'
          yscale: 'log'
          title: 'trap specie #1'
          xlabel: 'release time (s)'
          ylabel: 'density (cm$^{-3}$)'

detector:
  class: pyxel.detectors.ccd.CCD

  geometry:
    class: pyxel.detectors.ccd_geometry.CCDGeometry

    row:   579                      # compulsory
    col:   1                        # compulsory
    total_thickness: 10.0           # um
    pixel_vert_size: 42.            # um
    pixel_horz_size: 23.5           # um

  material:
    class: pyxel.detectors.material.Material
    material: 'silicon'

  environment:
    class: pyxel.detectors.environment.Environment
    temperature: 238                     # K

  characteristics:
    class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
    qe:   1.                 # -
    eta:  1.                # e/photon
    sv:   1.              # V/e
    amp:  1.                 # V/V
    a1:   1.                # V/V
    a2:   1               # DN/V
    fwc:  155000            # e
    fwc_serial: 1000000     # e
    vg:   9.87e-10          # cm2
    svg:  1.6200e-10         # cm2
    t:    141680e-09           # s
    st:   9.4722e-04          # s

pipeline:
  class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline

  # -> photons
  photon_generation:

    - name: load_profile
      func: pyxel.models.photon_generation.load_profile.load_profile
      enabled: true
      arguments:
        txt_file: data/flex/input/input_flex_ds7_ch0_1ke.txt
        fit_image_to_det: true
        convert_to_photons: false

  # photons -> photons
  optics:

  # photons -> charge
  charge_generation:
    - name: photoelectrons
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion
      enabled: true


  # charge -> charge
  charge_collection:
    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true

  # charge -> charge
  charge_transfer:

    - name: cdm
      func: pyxel.models.charge_transfer.cdm.CDM.cdm
      enabled: true
      arguments:
        parallel_cti: true
        serial_cti: false
        charge_injection: false
        beta_p: 0.3
        beta_s: 0.3
        tr_p: [.014]
        tr_s: [2.e-3]
        nt_p: [100.]
        nt_s: [50.]
        sigma_p: [1.e-12]
        sigma_s: [1.e-12]

  # charge -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true


  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true

    - name: simple_processing
      func: pyxel.models.readout_electronics.digitization.simple_processing
      enabled: true
